// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ecommerc_dotnet.context;

#nullable disable

namespace ecommerc_dotnet.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250505043350_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ecommerc_dotnet.module.User", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime?>("updated_at")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("NULL");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ecommerc_dotnet.module.User", b =>
                {
                    b.OwnsOne("ecommerc_dotnet.module.Person", "person", b1 =>
                        {
                            b1.Property<Guid>("ID")
                                .HasColumnType("uuid");

                            b1.Property<string>("address")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("email")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("name")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("phone")
                                .IsRequired()
                                .HasMaxLength(13)
                                .HasColumnType("character varying(13)");

                            b1.HasKey("ID");

                            b1.HasIndex("email", "phone")
                                .IsUnique();

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("ID");
                        });

                    b.Navigation("person")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
